/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonacionRouteImport } from './routes/donacion'
import { Route as MetalmecanicosRouteImport } from './routes/metalmecanicos'
import { Route as ProyectosSlugRouteImport } from './routes/proyectos/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonacionRoute = DonacionRouteImport.update({
  id: '/donacion',
  path: '/donacion',
  getParentRoute: () => rootRouteImport,
} as any)
const MetalmecanicosRoute = MetalmecanicosRouteImport.update({
  id: '/metalmecanicos',
  path: '/metalmecanicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosSlugRoute = ProyectosSlugRouteImport.update({
  id: '/proyectos/$slug',
  path: '/proyectos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donacion': typeof DonacionRoute
  '/metalmecanicos': typeof MetalmecanicosRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donacion': typeof DonacionRoute
  '/metalmecanicos': typeof MetalmecanicosRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donacion': typeof DonacionRoute
  '/metalmecanicos': typeof MetalmecanicosRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/donacion' | '/metalmecanicos' | '/proyectos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/donacion' | '/metalmecanicos' | '/proyectos/$slug'
  id: '__root__' | '/' | '/donacion' | '/metalmecanicos' | '/proyectos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonacionRoute: typeof DonacionRoute
  MetalmecanicosRoute: typeof MetalmecanicosRoute
  ProyectosSlugRoute: typeof ProyectosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donacion': {
      id: '/donacion'
      path: '/donacion'
      fullPath: '/donacion'
      preLoaderRoute: typeof DonacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metalmecanicos': {
      id: '/metalmecanicos'
      path: '/metalmecanicos'
      fullPath: '/metalmecanicos'
      preLoaderRoute: typeof MetalmecanicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$slug': {
      id: '/proyectos/$slug'
      path: '/proyectos/$slug'
      fullPath: '/proyectos/$slug'
      preLoaderRoute: typeof ProyectosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonacionRoute: DonacionRoute,
  MetalmecanicosRoute: MetalmecanicosRoute,
  ProyectosSlugRoute: ProyectosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
